### ISSUE TITLE
[DRAFT] Add feature to display filtered data on webapp

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#131]
### Overview
Add radio buttons to filter data via certain criteria.

### Action items
- [ ] Define which data to filter
- [ ] Create code to implement filtering
- [ ] Test locally and upload to AWS

### Resources/Instructions
Discuss with Greg

**Comment by gregpawin** [comment]
In icebox until further feature development discussed with product manager

**Comment by tmlin1** [comment]
@gregpawin  This issue has not had an update since 7/28/21.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
