### ISSUE TITLE
Add clustering feature to Mapbox

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#139]
### Overview
Use Mapbox tutorial to create clustering webapp feature. Our data consists of ~10 million rows. A clustering function would help speed up any slow downs caused by too much data being displayed. https://docs.mapbox.com/mapbox-gl-js/example/cluster/. It would be good to implement at a very low zoom level.

### Action items
- [ ] See if this can be implemented with current setup
- [ ] Test locally and upload to AWS

### Resources/Instructions
Discuss with Greg

**Comment by gregpawin** [comment]
Matthew was having problems with the geojson that was prepared for him. It was in the wrong map projection, so I created a new file and saved it to the Google Drive.

**Comment by mg78856** [comment]
<img width="1437" alt="Screen Shot 2020-07-27 at 12 54 11 PM" src="https://user-images.githubusercontent.com/42285261/88589939-c3201280-d00e-11ea-844f-dd8b6c77db8d.png">

https://docs.mapbox.com/mapbox-gl-js/example/cluster/

**Comment by qiqicodes** [comment]
We have heat map feature now. Closing this ticket.

**Comment by MichelleRT** [comment]
@[mg78856](https://github.com/mg78856) This issue has not had an update since July 28, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
