### ISSUE TITLE
[DRAFT] Develop webapp product requirements

### ISSUE THREAD

**Issue by gregpawin** [hackforla/lucky-parking#142]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
Develop and discuss lucky-parking webapp basic usage requirements, including basic functionality and aesthetics, for (please fill out: for Y REASON.)

### Action items
- [X] Discuss with team/product lead
- [ ] MVP will consist of heat map and data selection and visualization
  - [x] Heatmap
  - [ ] Data aggregation visualization
- [ ] Go back to with team/product lead
- [ ] Develop user personas
- [ ] Develop user surveys
- [ ] Interview users/stakeholders

### Resources/Instructions
Refer to Google Drive for previous work

**Comment by gregpawin** [comment]
For now--adding data point selection and data aggregation visualization features

**Comment by MichelleRT** [comment]
@gregpawin  This issue has not had an update since January 25, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by MichelleRT** [comment]
This issue is in the prioritized backlog, so we are going to un-assign Greg.

**Comment by ExperimentsInHonesty** [comment]
This issue is old, and may have been replaced by individual issues for UI/UX /Product  Re-evaluate once all the issues are on one board.

**Comment by gordonruby** [comment]
@ExperimentsInHonesty and @gregpawin I also think it's possible that this issue is old and so I won't prioritize this as a product manager issue without further context.
