### ISSUE TITLE
Create Color Palette

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#234]
Create a color palette for UX parking website. Please keep in mind accessibility (color contrast, color blindness) with both a dark and light mode website.

**Comment by MichelleRT** [comment]
@qiqicodes @salmonciara @DashaMaliarevska  This issue has not had an update since July 13, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
