### ISSUE TITLE
UX interviews - City Council Focus

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#235]
### Overview
Previous interviews were completed on individuals who lived in metropolitan areas and how they currently interact with parking/citations. 

A more focused user would be city council individuals looking to make a policy change within their community. What tools/report builder would be useful for them to complete this task

### Action

- [ ] Create problem statement/scope of research
- [ ] Create script for in-depth interview
- [ ] **STOP, work with data scientist/developers for buy-in**
- [ ] Create place to store data collected from interviews
- [ ] Analyze interviews
- [ ] create deck to present

### Resources 
Contact Kiki (@salmonciara) if you want to see the previously used questions for the first set of user interviews.  

Also in the Google Drive there is a research folder for reference

**Comment by MichelleRT** [comment]
@salmonciara  This issue has not had an update since August 2, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
