### ISSUE TITLE
Fix search bar for large and small mobile view

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#243]
### Overview
Current search bar overlaps the "from" date selector label for large mobile view, where window width is below 1250px. And date selector currently is not available for small mobile view. 

<details>
<summary>Desktop View - Good</summary>
<img src="https://user-images.githubusercontent.com/68657634/125398950-cd910480-e364-11eb-847f-99f64876c4bd.png">
</details>

<details>
<summary>iPad portrait view - Buggy</summary>
<img src="https://user-images.githubusercontent.com/68657634/125399486-86efda00-e365-11eb-98e3-94a0ada33448.png">
</details>

<details>
<summary>iPad landscape view - Buggy</summary>
<img src="https://user-images.githubusercontent.com/68657634/125399494-89523400-e365-11eb-94ab-a4832e0cb983.png">
</details>

<details>
<summary>iPhone - Buggy</summary>
<img src="https://user-images.githubusercontent.com/68657634/125402886-c0c2df80-e369-11eb-8f3e-de34302d9389.png">
</details>

<details>
<summary>Pixel - Buggy</summary>
<img src="https://user-images.githubusercontent.com/68657634/125402970-d6380980-e369-11eb-8980-00067f201677.png">
</details>

### Action Items
- [ ] fix overlapping search bar, make search bar mobile responsive
- [ ] make date selector available in mobile view

**Comment by MichelleRT** [comment]
@qiqicodes  This issue has not had an update since July 12, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
