### ISSUE TITLE
Display information card on mobile

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#244]
### Overview
Current ticket information slides in from the left on desktop view, and the information slides up on mobile view. Make cards fit all ticket information for mobile devices. 
<details>
<summary>Current Desktop View</summary>
<img src="https://user-images.githubusercontent.com/68657634/125404483-83f7e800-e36b-11eb-8d13-3ae795814f72.png">
</details>

<details>
<summary>Current Large Mobile View</summary>
<img src="https://user-images.githubusercontent.com/68657634/125405032-21ebb280-e36c-11eb-8e2d-4e7b94419ff3.png">
</details>

<details>
<summary>Current Small Mobile View</summary>
<img src="https://user-images.githubusercontent.com/68657634/125404941-0e404c00-e36c-11eb-8053-11c49edc7522.png">
</details>

### Action Items
- [ ] create card for mobile
- [ ] style

**Comment by rd-code-23** [comment]
Hi,

I might be able to help with this. 
So you basically, you want the font to be smaller for the ticket view on mobile devices, so all the info can fit on the screen?

**Comment by rd-code-23** [comment]
I might be able to help with this.
So basically, you want the rest of the information like Vehicle and fine amount to also be displayed on mobile view?

**Comment by qiqicodes** [comment]
Smaller and legible font sound good. And we need to design the card for mobile. 

Let me know if you would like to brainstorm styling together. We want to fit the content side by side. 

Something like this would be cool. 

https://drive.google.com/file/u/1/d/1Ndj8xdDUZ4agllS0k1UnLbVrhCBcCRzM/view?usp=drivesdk

**Comment by rd-code-23** [comment]
@qiqicodes 

How do I join your slack group?
 im having trouble getting this project to run on my computer.

**Comment by qiqicodes** [comment]
@rd-code-23 

please give this [link](https://hackforla.slack.com/?redir=%2Farchives%2FCPFDMSV6V) a try.

**Comment by rd-code-23** [comment]
@qiqicodes 

When I try to sign in and enter the workspace it give me an error saying I don't have an account on this workspace
Ill contact slack support to see how to fix it.

**Comment by MichelleRT** [comment]
@qiqicodes @rd-code-23  This issue has not had an update since August 3, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
