### ISSUE TITLE
[DRAFT] Switch for light/dark mode for mapbox

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#246]
### Overview
Add another mapbox style to application

### Action Items
- [ ] add switch
- [ ] add style

**Comment by tmlin1** [comment]
@qiqicodes This issue has not had an update since August 3, 2021. If you are no longer working on this issue please let us know.
If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue. We would appreciate it. If you are still working on the issue, please provide update using these guidelines

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by qiqicodes** [comment]
@tmlin1 I created this ticket to help the team in delivering features, I no longer work for Hack for LA and the lucky parking team.

This ticket doesn't have any assignee, feel free to assign this to any developer on the lucky parking team.

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
