### ISSUE TITLE
Create table, legend or a description that explains what Yellow Zone. 

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#257]
### Overview
Unclear what is the violation referring to.

### Action Items
Violation - Yellow Zone: Need a table or a description that explains what Yellow Zone. 

Green Zone: Low citation area
Yellow Zone: Medium citation area
Red Zone: High citation area

### Resources/Instructions
[UX Research and Next Steps](https://docs.google.com/presentation/d/10cOuppqzggkyqRw_d19lSxrtB-mUeqz_C790XoOe-yI/edit#slide=id.ge59ad16a7b_2_156)

**Comment by tmlin1** [comment]
@qiqicodes This issue has not had an update since August 3, 2021. If you are no longer working on this issue please let us know.
If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue. We would appreciate it. If you are still working on the issue, please provide update using these guidelines

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by qiqicodes** [comment]
https://github.com/hackforla/lucky-parking/issues/246#issuecomment-1075943315

**Comment by macho-catt** [comment]
Closing, since this is not applicable for the new design. Thanks
