### ISSUE TITLE
[DRAFT] Make icons larger

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#263]
### Overview
icons are hard to see

### Action Items
- [ ] Zoom in and out Icon 
- [ ] Graph Icon
- [ ] Trash Icon

**Comment by simzou** [comment]
These sizes are set by [`mapbox-gl.css`](https://github.com/hackforla/lucky-parking/blob/937ca7950d88509ec31e41b92bac6281e0daa6b7/js/client/public/index.html#L12) which we currently load in from mapbox.com. We'd have to override them and probably move this line down.

**Comment by tmlin1** [comment]
@qiqicodes This issue has not had an update since August 10, 2021. If you are no longer working on this issue please let us know.
If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue. We would appreciate it. If you are still working on the issue, please provide update using these guidelines

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by qiqicodes** [comment]
https://github.com/hackforla/lucky-parking/issues/246#issuecomment-1075943315

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
