### ISSUE TITLE
[DRAFT] Add pin/visual to indicate there is "Viewing Single citation information" 

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#264]
### Overview

When you click on a dot on the map, it provides the single citation. However there is nothing on the map that indicates there has been a change. The dot should be highlight a different colors, or there should be a pin on that dot to indicate that users are looking at a SINGLE citation information."

### Action Items
- [ ] add pin/visual for clicking
- [ ] change color

### Resources/Instructions
[UX Research and Next Steps](https://docs.google.com/presentation/d/10cOuppqzggkyqRw_d19lSxrtB-mUeqz_C790XoOe-yI/edit#slide=id.ge59ad16a7b_2_156)

**Comment by tmlin1** [comment]
@qiqicodes This issue has not had an update since August 3,2021. If you are no longer working on this issue please let us know.
If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue. We would appreciate it. If you are still working on the issue, please provide update using these guidelines

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
