### ISSUE TITLE
[DRAFT] Creating a history of searches

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#265]
### Overview
No history of search

### Action Items
Creating a history of searches

**Comment by simzou** [comment]
2 questions: 

Why do we want a history of searches? 
Is the scope of this to save the just the keyword history or combined keyword + date?

**Comment by qiqicodes** [comment]
UI/UX team wants to keep a record of the user's searches. To improve the user experience

**Comment by simzou** [comment]
So does that mean they want a history of searches displayed to the user or they want user searches captured on the backend for analysis or both?

**Comment by tmlin1** [comment]
@qiqicodes This issue has not had an update since 8/3/21.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
