### ISSUE TITLE
Reach out to Empower LA/Project manager for access to City Council Members

### ISSUE THREAD

**Issue by salmonciara** [hackforla/lucky-parking#269]
#### Overview
Refer to UX Interview - City Council Focus for detail on why we are recruiting/reaching out to other projects

### Action
- [x] Reach out to Empower LA
- [ ] Reach out to PM over all city council projects
- [ ] Advocate to have access to city council members to conduct research 

### Resources

Competitive analysis for other Hack for LA project: 
https://docs.google.com/spreadsheets/d/1V5cOCwABGNsvp715EL-SIRklcknEJB-hj4Mtjl8zMpw/edit#gid=259269486

**Comment by MichelleRT** [comment]
@salmonciara  This issue has not had an update since August 3, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by gordonruby** [comment]
@ymphan do you have any recent updates on this issue? Things like:

Progress: 
Blockers: 
Availability: 
ETA: 
Pictures (if necessary):

**Comment by ymphan** [comment]
@gordonruby 
No updates on this issue yet. I think maybe I could attend a meeting with you and Bonnie regarding this - creating a specific research group that can send out approved surveys to all neighborhood council members for Hack 4 LA.
