### ISSUE TITLE
Update Project One Sheet (& Basic Operating Procedures)

### ISSUE THREAD

**Issue by natenateo** [hackforla/lucky-parking#272]
### Overview
One Sheet: I have joined Lucky Parking as a new member or I am an existing member. By only looking at this document and without explanation, I am able to understand the type of project being built and its purpose.
Operating Procedures: I have joined Lucky Parking as a new member or I am an existing member. I understand the onboarding process, mission, meeting structure, member removal process, and roles of the project.

### Action Items
One Sheet
- [ ] Intro Copy (for one sheet & website project card)
- [ ] Mission
- [ ] Methods
- [ ] Values
Operating Procedures
- [ ] Meetings
- [ ] Onboarding
- [ ] Removal of Members

1. Rewrite One Sheet
2. Rewrite Operating Procedures
3. Get feedback from L.P. team
4. Finalize document and update Google Drive file

### Resources/Instructions
https://docs.google.com/document/d/1IJWkrbW7J1FleJ8drjzogDEMhXiTr4N-LKMknZhZYCA/edit?usp=sharing

**Comment by natenateo** [comment]
@salmonciara

**Comment by MichelleRT** [comment]
@natenateo @salmonciara  This issue has not had an update since August 10, 2021.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by MichelleRT** [comment]
Ciara responded (per email) with saying she and Nathan are no longer with the project and have not worked on the issue.
