### ISSUE TITLE
Fix Dependencies issue

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#275]
### Overview
Dependabot found potential security vulnerabilities in our dependencies. Figure out the codebase, whether some of the packages are necessary for our application.

### Action Items
- [ ] hosted-git-info
- [ ] lodash
- [ ] trim-newlines
- [ ] tar

**Comment by simzou** [comment]
Checked a couple of these: 
- `normalize-package-data` has `hosted-git-info` as a dependency, and about 50 packages have that as a dependency
- can't excise lodash, it's a dependency on 100+ packages in the client's `package-lock.json` including some pretty core ones like babel
- `trim-newlines` is a dependency of `meow` which is a dependency of some mapbox packages
- `tar` is a dependency of `node-gyp` which is a dependency of `node-sass`. We have a sass folder and our styles are in scss files but it doesn't look like we're compiling it anywhere to css. This project also will have relatively few pages so I don't know that sass is actually necessary. So this might be a candidate for removal.

**Comment by simzou** [comment]
Did a little more reading and so now I understand that `node-sass` allows to import a scss file in our react files so that's why we don't need to compile it. This apparently isn't considered [best practice](https://create-react-app.dev/docs/adding-a-sass-stylesheet/) and I don't think we're using that many sass features but it doesn't sound like a very fun job to strip it out. Ultimately probably easier to just update package.json to include the latest versions of these packages and hope that solves the problem.

**Comment by macho-catt** [comment]
This is related to #315, so I will close this.
