### ISSUE TITLE
[DRAFT] Display time series data for a selection

### ISSUE THREAD

**Issue by simzou** [hackforla/lucky-parking#277]
### Overview
One of the stated use cases for this app is to allow council members and urban planners analyze the effects of policy changes, changes in parking alignment, etc. have on citations. To that end it makes sense to display the time series data (i.e a line graph showing citations over time) for a given selection in addition to the aggregate data we currently show. We already have the notion of picking a date range built in. A bonus goal could be to actually build knowledge of specific dates where things changed if possible.

### Action Items

- [ ] UI / UX input
   - [ ] Get their feedback on this idea
   - [ ] Create wireframes / mockups for the additional data visualization
- [ ] Developer
   - [ ] Implement the design

**Comment by tmlin1** [comment]
@simzou This issue has not had an update since August 3, 2021. If you are no longer working on this issue please let us know.
If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue. We would appreciate it. If you are still working on the issue, please provide update using these guidelines

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by simzou** [comment]
I created this issue as a feature request for the app but never resourced it and am no longer working on this issue. Feel free to prioritize and/or assign to others.

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
