### ISSUE TITLE
[DRAFT] Add neighborhood layer

### ISSUE THREAD

**Issue by eugenecha** [hackforla/lucky-parking#285]
### Overview
Similar to the zip code layer we'd like to be able to view and select neighborhoods

### Action Items

- [ ] Neighborhood area to light up when selected 
- [ ] Neighborhood appears as the area lights up
- [ ] Show Neighborhood boundaries 

### Resources/Instructions
[Figma wireframe](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=135%3A7)
[Mapping sample](https://a816-dohbesp.nyc.gov/IndicatorPublic/Closerlook/geographies/index.html)

**Comment by tmlin1** [comment]
@macho-catt  This issue has not had an update since 2/22/22.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by macho-catt** [comment]
Progress: The table for neighborhood council is uploaded to the dev instance for testing. This is mostly done, and the only thing left to do is to transform the data to the proper format
    Blockers: n/a
    Availability: 2 hours
    ETA: This has become a lower priority compared to other work on the repo, but I can probably finish this in the next 2 weeks or so
    Pictures (if necessary): n/a

**Comment by macho-catt** [comment]
Un-assigning myself until I find more time to work on this.

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
