### ISSUE TITLE
Application Direction Optimization Suggestions

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#299]
### Overview
Application Direction Optimization Suggestions

### Action Items
- [x] Add a toggle/button (v) to display the instructions again.
- [ ] Optional: Instructions show on every refresh, instead should remember that they've been dismissed.
- [x] Instructions - mobile & tablet version (dependent UI design)

### Resources/Instructions
[Figma wireframe](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking?node-id=135%3A7)

**Comment by tmlin1** [comment]
@qiqicodes This issue has not had an update since September 13, 2021. If you are no longer working on this issue please let us know.
If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue. We would appreciate it. If you are still working on the issue, please provide update using these guidelines

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by qiqicodes** [comment]
https://github.com/hackforla/lucky-parking/issues/246#issuecomment-1075943315

**Comment by macho-catt** [comment]
The instructions has a toggle now, so closing this and will create new issues for the other two points if still necessary.
