### ISSUE TITLE
Query Bug: 

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/lucky-parking#306]
### Overview
Currently polygon tool and zip code tool don't take the datepicker's date in query. Fix this bug. =]
 
<details>
<summary>Query Bug</summary>
<img src="https://user-images.githubusercontent.com/68657634/135981904-29534314-e0f4-4d69-a46e-db092e917526.gif">
</details>

### Action Items
- [ ] Fix query for polygon tool
- [ ] Fix query for zip code tool

**Comment by tmlin1** [comment]
@macho-catt  This issue has not had an update since 2/20/22.  If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by macho-catt** [comment]
The backend implementation of the code is being worked on by @DCH-CH

**Comment by macho-catt** [comment]
PR to add modify the endpoint for filtering with datetime is currently under review. Please refer to #385 for the pr that aims to fix this.

**Comment by macho-catt** [comment]
backend is done, frontend needs to be worked on
