### ISSUE TITLE
[DRAFT] Implement Redis in our backend to optimize queries on repeated requests

### ISSUE THREAD

**Issue by macho-catt** [hackforla/lucky-parking#338]
### Overview
We need to optimize queries to our database by caching repeated queries.

### Action Items

- [ ] Review how Redis works, and discuss with the team if it is necessary, or if there are other viable caching solutions
- [ ] Gather data on how long each query (and repeated queries) on the database takes
- [ ] Implement Redis on the backend
    - [ ] Gather new data on how long repeated queries take with the caching solution
    - [ ] Demo to the team / lead
- [ ] Open a PR to implement Redis

### Resources/Instructions
https://github.com/redis/node-redis

**Comment by macho-catt** [comment]
Putting this in icebox for now, as there are possible optimizations on the frontend and the aws instance to host this on would not have enough storage / memory.

**Comment by gordonruby** [comment]
This issue is a DRAFT for now, but anyone can update the sections based on the format below, especially the Overview section. Once we know what needs to be done and why we can prioritize whether to work on this issue.

### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
