### ISSUE TITLE
Incorporate linters for the frontend code

### ISSUE THREAD

**Issue by macho-catt** [hackforla/lucky-parking#350]
### Dependency
#302 

### Overview
We need to incorporate linters for the frontend code to unify styling and minimize code errors.

### Action Items
- [ ] Discuss with the team / lead the rules we want to incorporate. Airbnb style guide is a good contender.
- [ ] Research and implement the following for the backend code
   - [ ] ESLint
   - [ ] Prettier
   - [ ] Husky
   - [ ] Lint-Staged
- [ ] Go through each file in the frontend and run the linter, correcting any errors
- [ ] Ensure that the website still functions as intended after the linting change

### Resource
[Airbnb Style Guide](https://github.com/airbnb/javascript/tree/master/react)

**Comment by tmlin1** [comment]
@macho-catt  This issue has not had an update since 2/22/22. If you are no longer working on this issue please let us know. 
 If you are able to give any closing comments related to why this issue stopped being worked on or if there are any other notes that never got added to the issue.  We would appreciate it.  If you are still working on the issue, please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by macho-catt** [comment]
This one is dependent on #302 and cannot be worked on until that is finished.

Thanks
