### ISSUE TITLE
[Frontend] Logo links to home route

### ISSUE THREAD

**Issue by glenflorendo** [hackforla/lucky-parking#624]
### User Story

As a user, I want the logo to link to the home route, so that I can easily navigate to the home page.

### Description

A popular convention in web development is to treat the logo, usually located in the header, as a link to the home page of the website.

We want to replicate this behavior in our web application.

Be mindful that, in React Router, the page may not navigate because the new route doesn't change (as is in our case). You may need to read through the docs to ensure that the page is always navigated regardless.

### Acceptance Criteria

1. The full logo is linked to the home route.
2. Clicking anywhere on the logo navigates to the home route.

### Technical References

- [React Router](https://reactrouter.com/en/main)

**Comment by dannycpham** [comment]
@bzzz-coding Hi there! Thanks for your work on this. Can you also make sure that it would navigate to the homepage even if we're on the home page already. Basically resetting lucky parking. :)

**Comment by bzzz-coding** [comment]
@dannycpham Hi Danny, I thought by setting the reloadDocument to true, the page would do a reload even if the user is currently on the home page. The Link wrapping the logo should now act like an anchor link, which reloads the page. Maybe I misunderstood the request... Could you help me understand why we want to reload the page instead of only re-render updated components?
